// Optional front-end allowlist for UI (real security is in Firestore rules)
export const ADMIN_EMAILS: string[] = (import.meta.env.VITE_ADMIN_EMAILS || '')
  .split(',')
  .map((s: string) => s.trim())
  .filter(Boolean)
