-- Tabla: academy_payments
-- Exportada desde Firestore colección: academy_payments
-- Total de registros: 81

CREATE TABLE IF NOT EXISTS academy_payments (
  id TEXT PRIMARY KEY,
  invoiceId TEXT,
  createdAt TIMESTAMPTZ,
  amount BIGINT,
  studentId TEXT,
  method TEXT
);

-- Datos
BEGIN;

INSERT INTO academy_payments (id, invoiceId, createdAt, amount, studentId, method) VALUES ('0Aa7n8qY3i3E256gvTox', 'QDE46Zl4gRFsXHYHQdDy', '2025-08-16T16:49:13.173Z', 40, 'uIlO3wT2gPrnMM82ZJKg', 'cash') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, studentId, method, amount, createdAt, invoiceId) VALUES ('0HxrvywQyuxjggypThDD', 'TYJIiSz6GYuYyxKav4FA', 'cash', 4, '2025-08-23T16:49:19.454Z', 'WRmW9GxhPOcNTDclADo4') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, studentId, method, amount, invoiceId, createdAt) VALUES ('16hJUuZlnYbYhwWG02GF', 'ef6bcFPlK58pWXgZK7O2', 'zelle', 80, 'eQIHQdGgTabjsOlESjr9', '2025-08-23T17:14:49.792Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, createdAt, invoiceId, studentId, method) VALUES ('2D2fWm6oIdKHHlZ0HLfh', 40, '2025-08-16T16:38:56.693Z', '17QMqxUegBQHDxSj4oWc', 'gqf8PIPsnBDIKB5XtE0i', 'cash') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, amount, method, createdAt, invoiceId, studentId) VALUES ('2dnZgRg57DBQoYupHpJC', 40, 'cash', '2025-08-30T18:12:21.026Z', '3d4SgW6NRPh1saleUCB3', '0pls9v9mBdxaDs9gvezQ') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, method, invoiceId, amount, studentId, createdAt) VALUES ('2w5nPfkmfjAGcApbVLvN', 'cash', 'JYjQ1k5MJ3C5A94MwXHs', 40, 'IpbYJ0LgIL8ka4bGrvAr', '2025-08-30T14:55:01.852Z') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, method, createdAt, studentId, invoiceId) VALUES ('4oo0GRP432GOVz7SgPRI', 80, 'zelle', '2025-08-16T14:02:17.183Z', 'cZFQDbZ2AkCxEbfbmLk9', 'eX96X02hFtpNcPkBfWQt') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, createdAt, invoiceId, method, studentId, amount) VALUES ('4p3yo49Er0iO584Q3ai4', '2025-08-23T17:28:29.296Z', 'M5NqyP5prX3kiUDGDiwE', 'zelle', 'SeX7CVtj7cofIGhBc3IM', 40) ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, method, studentId, createdAt, amount, invoiceId) VALUES ('4w22bBa43N6H3sdL8CgT', 'zelle', 'ML3Qmv15anbwGz53iOGh', '2025-11-15T17:54:48.947Z', 40, 'G0eeb86LstedFPT9XJws') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, amount, studentId, invoiceId, createdAt, method) VALUES ('51mXtG0aPYc4ycyh7rLZ', 80, 'ZrG3rWnTOErqpYHsNcrI', 'HZTuPTPlLzgXDxr0nbfT', '2025-08-16T14:12:19.052Z', 'zelle') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, method, amount, createdAt, studentId) VALUES ('5mfLxh2vDeLVlfge957H', 'SpHtoAS32lpWuOSbG6GV', 'discount', 0, '2025-08-19T03:50:35.759Z', 's1r39eJN6MdBEI1bT9rz') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, createdAt, studentId, method, invoiceId, amount) VALUES ('6nfzXsWUTTTLtOjp00Jd', '2025-08-16T14:00:19.512Z', 'udpngi30PaSxrVMLIq8v', 'zelle', 'sHED5xhlewiAIqtJmLuO', 40) ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, invoiceId, createdAt, amount, studentId, method) VALUES ('89VZqrJUE5zDKDiutlWl', 'l4Bqib5Inv2xSmYG7hry', '2025-08-16T16:53:26.054Z', 160, 'ykYwTu32jtdwk1gFz20W', 'zelle') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, createdAt, method, invoiceId, studentId, amount) VALUES ('94A3WFlB7TZ86JYKUgQu', '2025-08-16T13:44:41.888Z', 'cash', 'yRiJCIi8b4oTGp0kbxGF', 'JYkVo8Qm5N5H7Sw3wfO4', 40) ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, invoiceId, studentId, amount, method, createdAt) VALUES ('9OAHwkTfjwiKalLQDBmw', '8J0U1qrnwoNvnqcqZi7d', 'RBgkAt1DKRYAE8yL93Dd', 40, 'zelle', '2025-08-16T16:54:09.422Z') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, method, createdAt, invoiceId, amount, studentId) VALUES ('AJZwfUT6U4DxBk97ncz5', 'zelle', '2025-08-30T16:48:52.480Z', 'RL6rkFYiq3eRKaCGTnkM', 40, 'sW9YUQ7mh5g4f5I2MTWz') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, method, createdAt, amount, studentId, invoiceId) VALUES ('AtJ1LoLXD5kK5cbUjyvk', 'zelle', '2025-08-30T16:43:33.994Z', 150, 'Y5LVFtDZykWpmyyxO6m4', '4QUHtFPHICsG59kieb8B') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, amount, studentId, createdAt, method, invoiceId) VALUES ('BoZjR4f6i3EqlsscIMdy', 40, 'sW9YUQ7mh5g4f5I2MTWz', '2025-08-23T14:03:34.860Z', 'cash', 'RL6rkFYiq3eRKaCGTnkM') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, amount, invoiceId, method, createdAt, studentId) VALUES ('CAMyvnXh0ORW3sNusfNP', 160, 'W6OLV7ECWqtMjEQKTQNb', 'cash', '2025-08-16T13:20:40.733Z', 'HyyIL7cqWXkaw15rFlek') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, createdAt, invoiceId, studentId, amount, method) VALUES ('CQYbWRiKao1foFtfzjl9', '2025-08-23T16:49:56.885Z', 'WRmW9GxhPOcNTDclADo4', 'TYJIiSz6GYuYyxKav4FA', 40, 'zelle') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, method, studentId, amount, invoiceId, createdAt) VALUES ('D3B0MUWk7h4QCXKSgH39', 'cash', 'TDPfWeQd8cgDn6W3642R', 140, 'ntEN3FyoGudXsBjk8PpS', '2025-08-16T16:41:12.639Z') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, createdAt, studentId, method, amount, invoiceId) VALUES ('DrOcPiWOFpzwJV63q79x', '2025-09-07T12:55:44.127Z', '8m6Gq3xal2qcLLQoR14x', 'zelle', 40, 'GBpW3SNUG599jZfCL89s') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, studentId, invoiceId, createdAt, amount, method) VALUES ('FYceKGIhKYDeZLgW8Y4u', 't4u0mkEfjTmrM40Olcmd', 'AZIFkdMR5X2cLirHKla2', '2025-08-23T17:15:10.223Z', 80, 'zelle') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, studentId, method, invoiceId, createdAt, amount) VALUES ('FtXgo5J6vUCBDpqYJ2Ss', 'dHNloK54dHDSmmSctNxh', 'cash', 'Pm7BVuEHBpv9gWaIW1h8', '2025-08-16T13:21:57.549Z', 160) ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, studentId, createdAt, invoiceId, method, amount) VALUES ('GkwcsXmJ2Ujtnb6pqnzo', 'eW9NVCRM4iynPBvbO0hI', '2025-08-16T16:53:47.556Z', 'EAKHXqimO6ZOjUOIHZUA', 'zelle', 160) ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, invoiceId, createdAt, amount, studentId, method) VALUES ('HydSDL4aWtw9ZFnVbwGR', 'CUIqs54PuqAaIxbhRd64', '2025-08-16T13:53:52.850Z', 80, 'VRFaM9vRZgNrQGHO5XWv', 'zelle') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, method, amount, studentId, createdAt) VALUES ('IiK7H2JFtCGPq5zHChbX', 'r3pZBMsqxtposlIXcC4C', 'zelle', 40, 'z3Em9fs7cxFrmI2VItjh', '2025-08-16T14:15:02.283Z') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, studentId, amount, createdAt, method, invoiceId) VALUES ('KWg2xf4Da88Y5GAnQPSr', 'Q5adfhVSV6SMrsggelWq', 40, '2025-08-23T16:40:42.060Z', 'cash', 'RQNBQk731o9qz6bYEAqM') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, invoiceId, studentId, createdAt, amount, method) VALUES ('MbETLRb56vifhx1e2TMI', 'DUZ81yqgeX5cyRKkrz0s', '5gxKZV3G7kbQaZEaFdmJ', '2025-08-16T13:31:14.628Z', 40, 'cash') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, studentId, invoiceId, createdAt, method, amount) VALUES ('O252eFQ64Rmn1HFrVX6K', 'TYJIiSz6GYuYyxKav4FA', 'uStAv4SKkgJ5WtySfMLR', '2025-09-07T12:59:35.096Z', 'zelle', 4) ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, studentId, method, amount, invoiceId, createdAt) VALUES ('OCh1HV9YG2a8RCxpFUTn', 'NqOOBUpgfVRdVa2W6VTX', 'cash', 40, '2Zts0pLe9QLY377qZSsM', '2025-08-30T18:12:43.140Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, studentId, invoiceId, amount, method, createdAt) VALUES ('ODQBdzURPQo7eL9HquQ4', 'bGieR4EAzV1XYBhRyCsK', 'sVERmf10ShR4beoSVmfY', 80, 'zelle', '2025-08-16T13:34:00.028Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, method, amount, studentId, createdAt, invoiceId) VALUES ('ObvW3qTFrN6UP5ZYJmJx', 'cash', 11, 'uOxhfCSMo6x5nDv8kUpU', '2025-08-30T16:54:32.622Z', 'J8BIKtV34HUJQK6OZEtV') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, method, createdAt, studentId, amount, invoiceId) VALUES ('PraPUfAc5jxQaAaKyOOB', 'cash', '2025-08-16T13:46:31.469Z', 'jOG7fIXzF3mUklKc7bqu', 40, 'LI2GGVu0pfULpRi9tiB7') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, createdAt, invoiceId, studentId, amount, method) VALUES ('Q5tqX9NlBBbUBlyVqUzy', '2025-08-19T03:50:11.158Z', 'q5ugrhqTUtzJzZe2SLFC', 'm9BzmhATRzC2Vs4ErB2e', 0, 'discount') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, amount, studentId, method, invoiceId, createdAt) VALUES ('QU27DZpiRcAjeJTXi0vB', 4, 'ef6bcFPlK58pWXgZK7O2', 'zelle', '9LwgBGbQNFjzMt0EGuad', '2025-08-24T01:46:16.808Z') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, createdAt, invoiceId, method, studentId) VALUES ('V2WDm2qYup2C31g0WTi4', 40, '2025-09-06T14:00:37.997Z', '5FtVCmziQ6CszctG4yh9', 'cash', 'QPhi9B0R0xisU9mf9TFT') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, invoiceId, amount, studentId, createdAt, method) VALUES ('WeMQUk5y24aq8MOoOpcM', 'NFYSNHPhCEqNpvUvEwhS', 40, 'OoXZzbFACPdqA86MSyqQ', '2025-08-16T13:27:56.917Z', 'cash') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, method, studentId, createdAt, amount, invoiceId) VALUES ('XiAqgHijZCYefIjIpaUN', 'zelle', 'STe4X94rt08PRieGGTtA', '2025-08-16T13:54:48.667Z', 160, 'Dcd0JNYBUqNFVmqiXLEM') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, studentId, amount, method, createdAt, invoiceId) VALUES ('XjDIkzfhKLPRMstP5jlS', 'LYORjaQ0jFXfAi7US0Cj', 40, 'cash', '2025-08-16T13:39:50.867Z', 'MGzuKp9tDXfVfW6sUqMR') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, method, amount, invoiceId, createdAt, studentId) VALUES ('Y0TuP6AnHBz8NXTJng2o', 'zelle', 80, 'LaTuWctidfdzSAuiUonk', '2025-08-16T16:11:31.921Z', 'XrQ6yIVC9M3aaR85SXiD') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, createdAt, invoiceId, studentId, amount, method) VALUES ('YUgXtYRkrBRXvxqvsc6M', '2025-08-16T13:54:15.840Z', 'gmJcWWl0DpQgP19T4Xso', 'GIcw7A1x6eua1XPh8tGL', 80, 'zelle') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, studentId, amount, method, createdAt, invoiceId) VALUES ('bMIMfms1FJjFylSsEkvr', 'JXW2eIxLt7ySoqgg2ePB', 230, 'zelle', '2025-08-16T16:44:56.337Z', 'gG91cbFYZsx8GubjKmWZ') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, createdAt, studentId, amount, method, invoiceId) VALUES ('d1XfrScpk7IsRt5snLGA', '2025-08-23T17:13:29.043Z', 'ckcU9GcQLYXwsMexNNyh', 40, 'zelle', 'zfolflBu1857ps7qllz4') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, createdAt, studentId, invoiceId, amount, method) VALUES ('dvJEjQYNZOYSjEkeHTcJ', '2025-08-16T14:04:56.584Z', 'UfjeabXHAkBC5sOAPuPY', 't8FPwu1r157ZFcyLShdF', 40, 'cash') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, createdAt, method, studentId, amount) VALUES ('evFT3Ls1UQfD3VM9nzfr', 'XcdQchvFoRe4FnmvYzzk', '2025-08-19T03:51:06.978Z', 'discount', '1Eg9SLYotnCAXnX2qZZV', 0) ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, createdAt, studentId, amount, invoiceId, method) VALUES ('exsdrHRZVmbFMlhQDVbw', '2025-08-16T16:45:14.421Z', 'Y5LVFtDZykWpmyyxO6m4', 20, 'k7Lhl8P84GAMkLdXxIPa', 'zelle') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, method, amount, createdAt, studentId) VALUES ('fUsJbNIONDauU31e1R8j', 'gJcokagwQtWFrSFe1Eyo', 'zelle', 8, '2025-09-13T16:30:54.256Z', 'XrQ6yIVC9M3aaR85SXiD') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, method, amount, studentId, createdAt, invoiceId) VALUES ('gCLgNfhb8yTDZqMSadNy', 'cash', 44, 'W82qx6S8pHzrYHAn0RQT', '2025-09-13T16:49:53.481Z', 'Iy4gDHS6TiFPOLCbQdqI') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, studentId, amount, method, createdAt, invoiceId) VALUES ('gkVRkdWq0KPvlHwBPuwU', 'B64sAJoNkcrdNyoci4b2', 80, 'zelle', '2025-08-24T01:17:01.260Z', 'XPN0tioZAA5Kmo9H61wH') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, amount, invoiceId, method, studentId, createdAt) VALUES ('hGWAGyXR3jZthZaj5aGV', 4, 'TBzh9j47fGntjIDJgJ5b', 'zelle', '0okB4ACOsyjkAqJBVUvk', '2025-08-30T13:34:13.150Z') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, studentId, amount, createdAt, invoiceId, method) VALUES ('hp3FGK1kdmTI7Crugazl', 'uOxhfCSMo6x5nDv8kUpU', 80, '2025-08-16T16:11:52.937Z', 'VyiUvYC4OHR1BvgfVy9L', 'zelle') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, studentId, amount, createdAt, method) VALUES ('jWHJuVetHnDDGT37m7qq', 'QDE46Zl4gRFsXHYHQdDy', 'uIlO3wT2gPrnMM82ZJKg', 40, '2025-08-23T17:06:24.338Z', 'cash') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, amount, invoiceId, method, createdAt, studentId) VALUES ('jjiNmrIrXIz4BYhm0Iwc', 40, 'HldXrLzrFA7DjgQq7eBF', 'cash', '2025-08-16T14:09:29.680Z', 'aeEGP9Fy5j5O4vnLqsXG') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, createdAt, amount, invoiceId, method, studentId) VALUES ('lTPIniV6CMSQc8qElz7z', '2025-08-23T17:26:21.113Z', 80, 'pD6Bcdr3z9zyScdwvCba', 'zelle', 'yJR9UD2ZaCLVTrkDX9ta') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, invoiceId, amount, studentId, createdAt, method) VALUES ('n8sHHfLokNGCPtfukLI7', 'e1Uod0oCWalYq1x4XcyQ', 4, 't4u0mkEfjTmrM40Olcmd', '2025-08-23T17:15:24.639Z', 'zelle') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, method, invoiceId, createdAt, studentId, amount) VALUES ('njFhNR7fbDcC7H0S37ib', 'cash', 'vbhG9p5N2X4T8F568q4F', '2025-08-16T13:19:17.124Z', 'O6EBmoLButunFIHLV9zN', 80) ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, createdAt, invoiceId, studentId, amount, method) VALUES ('o2TaSBbxBg51H1IH639O', '2025-08-16T13:40:37.816Z', 'nSyRatQhbIwQ5UMjtMin', 'DQhaqMwJZ1WzCJ8ccnxv', 40, 'cash') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, createdAt, invoiceId, studentId, amount, method) VALUES ('o6612oM9THvlQhZA1lk0', '2025-08-16T17:15:49.286Z', 'Z8mgEXEGZzOKefrAiSGk', 'cZFQDbZ2AkCxEbfbmLk9', 80, 'zelle') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, method = EXCLUDED.method;
INSERT INTO academy_payments (id, createdAt, method, invoiceId, amount, studentId) VALUES ('o8YCgTYKV6n2pHsivwmJ', '2025-08-16T13:42:04.594Z', 'zelle', 'cp8CeBgKfiiDOmVhbJJW', 80, '5gxKZV3G7kbQaZEaFdmJ') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, createdAt, method, amount, studentId, invoiceId) VALUES ('oLz9w2shtmD5WKKm9Chy', '2025-08-16T14:03:10.098Z', 'cash', 40, 'DMQrSDAeumcPjiHZmuBW', 'EEis6tiqQc9fyAFTGWUb') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, invoiceId, method, createdAt, studentId, amount) VALUES ('oNmxZGTIRgzZwk4fcxgG', '1hWrEigKFHXZwaykvDcg', 'cash', '2025-08-23T13:50:43.927Z', 'B98IoYc22v4n9TWDxHDy', 40) ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, amount, method, invoiceId, createdAt, studentId) VALUES ('oS5ve4HA8wzA52id1BRP', 40, 'cash', '6P6fBhwM6hfgis5lQbmh', '2025-08-30T16:40:17.017Z', 'vJMkFxOAY1eshv9NEQ5E') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, method = EXCLUDED.method, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, amount, invoiceId, studentId, method, createdAt) VALUES ('p5zUL06azyXyVIlsB2J1', 80, '2QlQkVwrvnnaYNfV81Sr', 'D752xPveJpvQ7LwS4ltv', 'zelle', '2025-08-16T16:12:09.819Z') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, method, createdAt, amount, studentId, invoiceId) VALUES ('p9KWpbyMAnXz0yjjJk5n', 'discount', '2025-08-19T03:50:55.104Z', 0, 'Nm252oBpkiu5hRmhfrG1', 'qK1MJzFK8xSUAv9AKRM3') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, invoiceId, studentId, amount, createdAt, method) VALUES ('pOtIxqTCf1OcYhRamL8j', '4KU8jXtqDGGPch7UTQiZ', 'ML3Qmv15anbwGz53iOGh', 40, '2025-11-15T17:54:48.886Z', 'zelle') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, method, amount, studentId, createdAt) VALUES ('pk28rEFTgoHXoRvjxE7L', '9UxcJYTHXqb1p46Bh6cH', 'zelle', 150, 'ML3Qmv15anbwGz53iOGh', '2025-11-15T17:54:48.794Z') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, createdAt, method, studentId, invoiceId) VALUES ('serOYaQXcf283wqSuBbJ', 40, '2025-08-16T14:54:32.454Z', 'zelle', 'hgSaMrYxz5Jo29Fg1X6u', 'PtXnUgl9zyqcw36hYdGS') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, studentId, method, createdAt, invoiceId, amount) VALUES ('tGSAAenb6ycaHtc7PVoL', 'u8nlklZ6mbJdN1wp7pBI', 'zelle', '2025-08-23T17:20:22.229Z', 'yD02XXE1d57Pz80XNBaB', 4) ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount;
INSERT INTO academy_payments (id, method, createdAt, amount, invoiceId, studentId) VALUES ('tn7mSqyxIr2OPe2uAarO', 'cash', '2025-08-16T13:24:00.704Z', 84, 'Y1Q5i5ELTmB3g9udEV0m', 'Q5adfhVSV6SMrsggelWq') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, method, amount, studentId, createdAt, invoiceId) VALUES ('uRciJLGDOBoiifBaUwuh', 'zelle', 120, 'FCIbwvWc8HPydPYepWBr', '2025-08-16T13:53:31.166Z', '1E7tKXb1Q7izVTGULPSX') ON CONFLICT (id) DO UPDATE SET method = EXCLUDED.method, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, invoiceId, method, createdAt, amount, studentId) VALUES ('ulTjmZdCfYBfLTAOAM3d', 'LvOyhbVb0kV9ibkQePL3', 'zelle', '2025-08-16T13:57:19.659Z', 190, '0okB4ACOsyjkAqJBVUvk') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, amount = EXCLUDED.amount, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, studentId, amount, invoiceId, method, createdAt) VALUES ('viWKs69u8twYlGIdT6oK', 'TYJIiSz6GYuYyxKav4FA', 4, 'FhYhC8rGvNAyUnYk79vW', 'zelle', '2025-09-13T16:42:31.613Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, createdAt, invoiceId, method, studentId) VALUES ('wBK2JeXW8IpVQP4OWMqk', 120, '2025-08-16T13:53:10.575Z', 'I6lWVvLdJBHrtf2r484A', 'zelle', 'Qq6rndQN0lYgZG1HX4Co') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, studentId, method, amount, invoiceId, createdAt) VALUES ('wkFR5vznZFhVwI3XExtR', '0okB4ACOsyjkAqJBVUvk', 'zelle', 4, 'djFuLVt5pUKWifbW6wBw', '2025-08-24T02:05:00.809Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, amount, studentId, method, createdAt, invoiceId) VALUES ('xLHTpQVr3CR4eoTugxym', 0, 's1r39eJN6MdBEI1bT9rz', 'discount', '2025-08-19T03:28:21.756Z', 'FTHCbra5IfUbP0AogP60') ON CONFLICT (id) DO UPDATE SET amount = EXCLUDED.amount, studentId = EXCLUDED.studentId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId;
INSERT INTO academy_payments (id, createdAt, method, amount, invoiceId, studentId) VALUES ('xtx4mGKbSu5i6QXe4Rq2', '2025-08-23T13:27:48.446Z', 'cash', 50, 'ntEN3FyoGudXsBjk8PpS', 'TDPfWeQd8cgDn6W3642R') ON CONFLICT (id) DO UPDATE SET createdAt = EXCLUDED.createdAt, method = EXCLUDED.method, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, studentId = EXCLUDED.studentId;
INSERT INTO academy_payments (id, studentId, amount, invoiceId, createdAt, method) VALUES ('yqDop1JvLXRNbwfme29t', 'm9BzmhATRzC2Vs4ErB2e', 0, 'dcrhx32q8nRS9hmJJv3S', '2025-08-19T03:17:23.317Z', 'discount') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, invoiceId = EXCLUDED.invoiceId, createdAt = EXCLUDED.createdAt, method = EXCLUDED.method;
INSERT INTO academy_payments (id, invoiceId, method, studentId, amount, createdAt) VALUES ('zK18JG2wCjQqParVUiPg', 'hJhjbGi6NdsopSnkFAJh', 'cash', 'aeEGP9Fy5j5O4vnLqsXG', 44, '2025-08-30T13:40:54.761Z') ON CONFLICT (id) DO UPDATE SET invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, studentId = EXCLUDED.studentId, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, studentId, invoiceId, method, amount, createdAt) VALUES ('zMZ1eiKTrfZFcoCzzfQX', 'Y5LVFtDZykWpmyyxO6m4', 'k7Lhl8P84GAMkLdXxIPa', 'cash', 100, '2025-08-16T14:45:19.695Z') ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, invoiceId = EXCLUDED.invoiceId, method = EXCLUDED.method, amount = EXCLUDED.amount, createdAt = EXCLUDED.createdAt;
INSERT INTO academy_payments (id, studentId, method, createdAt, invoiceId, amount) VALUES ('zrlLJqjYdSaeiNsjflRG', 'u8nlklZ6mbJdN1wp7pBI', 'zelle', '2025-08-23T17:20:06.460Z', 'Pyvzg2zr2ovIw6df5vD7', 80) ON CONFLICT (id) DO UPDATE SET studentId = EXCLUDED.studentId, method = EXCLUDED.method, createdAt = EXCLUDED.createdAt, invoiceId = EXCLUDED.invoiceId, amount = EXCLUDED.amount;

COMMIT;

