-- Tabla: volunteer_hours
-- Exportada desde Firestore colección: volunteer_hours
-- Total de registros: 6

CREATE TABLE IF NOT EXISTS volunteer_hours (
  id TEXT PRIMARY KEY,
  eventName TEXT,
  checkInTime TIMESTAMPTZ,
  updatedAt TIMESTAMPTZ,
  volunteerName TEXT,
  totalHours NUMERIC,
  eventId TEXT,
  volunteerEmail TEXT,
  createdAt TIMESTAMPTZ,
  checkInLocation JSONB,
  checkOutLocation TEXT,
  checkOutTime JSONB,
  volunteerId TEXT,
  status TEXT
);

-- Datos
BEGIN;

INSERT INTO volunteer_hours (id, eventName, checkInTime, updatedAt, volunteerName, totalHours, eventId, volunteerEmail, createdAt, checkInLocation, checkOutLocation, checkOutTime, volunteerId, status) VALUES ('JQ9203AMJvXWw9xuaF7F', 'Taste of Korea - Pre-Event Preparation Period', '2025-10-31T13:08:39.625Z', '2025-11-03T20:18:13.412Z', 'Jod', 12.86, 'taste-of-korea-preparation', 'ing.jod@gmail.com', '2025-10-31T13:08:39.625Z', '{"latitude":28.809608082214023,"longitude":-81.26825257191402,"_type":"geopoint"}'::jsonb, NULL, '{"seconds":1761962400,"nanoseconds":0}'::jsonb, 'PBGCLV', 'checked-out') ON CONFLICT (id) DO UPDATE SET eventName = EXCLUDED.eventName, checkInTime = EXCLUDED.checkInTime, updatedAt = EXCLUDED.updatedAt, volunteerName = EXCLUDED.volunteerName, totalHours = EXCLUDED.totalHours, eventId = EXCLUDED.eventId, volunteerEmail = EXCLUDED.volunteerEmail, createdAt = EXCLUDED.createdAt, checkInLocation = EXCLUDED.checkInLocation, checkOutLocation = EXCLUDED.checkOutLocation, checkOutTime = EXCLUDED.checkOutTime, volunteerId = EXCLUDED.volunteerId, status = EXCLUDED.status;
INSERT INTO volunteer_hours (id, status, eventName, createdAt, updatedAt, volunteerName, volunteerId, checkInLocation, totalHours, checkInTime, checkOutTime, checkOutLocation, volunteerEmail, eventId) VALUES ('KlY8FqEDrPyELd1H3j5N', 'checked-out', 'Taste of Korea - Pre-Event Preparation Period', '2025-10-28T23:01:01.290Z', '2025-10-28T23:05:11.884Z', 'Jod', 'D24SOJ', '{"latitude":28.8129024,"longitude":-81.26464,"_type":"geopoint"}'::jsonb, 0.07, '2025-10-28T23:01:01.290Z', '2025-10-28T23:05:11.884Z', '{"latitude":28.8129024,"longitude":-81.26464,"_type":"geopoint"}'::jsonb, 'jlouis@iyfusa.org', 'taste-of-korea-preparation') ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, eventName = EXCLUDED.eventName, createdAt = EXCLUDED.createdAt, updatedAt = EXCLUDED.updatedAt, volunteerName = EXCLUDED.volunteerName, volunteerId = EXCLUDED.volunteerId, checkInLocation = EXCLUDED.checkInLocation, totalHours = EXCLUDED.totalHours, checkInTime = EXCLUDED.checkInTime, checkOutTime = EXCLUDED.checkOutTime, checkOutLocation = EXCLUDED.checkOutLocation, volunteerEmail = EXCLUDED.volunteerEmail, eventId = EXCLUDED.eventId;
INSERT INTO volunteer_hours (id, status, eventName, createdAt, volunteerEmail, checkOutLocation, updatedAt, checkInTime, totalHours, eventId, checkInLocation, volunteerName, volunteerId, checkOutTime) VALUES ('LmsfKPPTLWhkpbiZcYg6', 'checked-out', 'Taste of Korea - Pre-Event Preparation Period', '2025-10-30T22:33:06.489Z', 'danielchoi0423@gmail.com', NULL, '2025-11-03T20:18:40.333Z', '2025-10-30T22:33:06.489Z', 3.45, 'taste-of-korea-preparation', '{"latitude":28.8094109,"longitude":-81.268335,"_type":"geopoint"}'::jsonb, 'Daniel', 'UFOO23', '{"seconds":1761876000,"nanoseconds":0}'::jsonb) ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, eventName = EXCLUDED.eventName, createdAt = EXCLUDED.createdAt, volunteerEmail = EXCLUDED.volunteerEmail, checkOutLocation = EXCLUDED.checkOutLocation, updatedAt = EXCLUDED.updatedAt, checkInTime = EXCLUDED.checkInTime, totalHours = EXCLUDED.totalHours, eventId = EXCLUDED.eventId, checkInLocation = EXCLUDED.checkInLocation, volunteerName = EXCLUDED.volunteerName, volunteerId = EXCLUDED.volunteerId, checkOutTime = EXCLUDED.checkOutTime;
INSERT INTO volunteer_hours (id, status, volunteerId, eventId, volunteerEmail, volunteerName, totalHours, updatedAt, createdAt, checkOutTime, checkInTime, checkInLocation, checkOutLocation, eventName) VALUES ('VCy4rObpeP1fm3gFpDMS', 'checked-out', 'PBGCLV', 'taste-of-korea-preparation', 'ing.jod@gmail.com', 'Jod', 10.18, '2025-10-29T23:10:31.123Z', '2025-10-29T12:59:58.425Z', '2025-10-29T23:10:31.123Z', '2025-10-29T12:59:58.425Z', '{"latitude":28.80947538864202,"longitude":-81.26839966368455,"_type":"geopoint"}'::jsonb, '{"latitude":28.80975704934022,"longitude":-81.26877935065025,"_type":"geopoint"}'::jsonb, 'Taste of Korea - Pre-Event Preparation Period') ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, volunteerId = EXCLUDED.volunteerId, eventId = EXCLUDED.eventId, volunteerEmail = EXCLUDED.volunteerEmail, volunteerName = EXCLUDED.volunteerName, totalHours = EXCLUDED.totalHours, updatedAt = EXCLUDED.updatedAt, createdAt = EXCLUDED.createdAt, checkOutTime = EXCLUDED.checkOutTime, checkInTime = EXCLUDED.checkInTime, checkInLocation = EXCLUDED.checkInLocation, checkOutLocation = EXCLUDED.checkOutLocation, eventName = EXCLUDED.eventName;
INSERT INTO volunteer_hours (id, eventName, checkInLocation, volunteerId, eventId, createdAt, volunteerName, volunteerEmail, status, updatedAt, checkInTime) VALUES ('bHQgeoZAfjujZmlRsrOG', 'Taste of Korea - Pre-Event Preparation Period', '{"latitude":28.8063488,"longitude":-81.26464,"_type":"geopoint"}'::jsonb, 'PBGCLV', 'taste-of-korea-preparation', '2025-11-03T20:14:31.866Z', 'Jod', 'ing.jod@gmail.com', 'checked-in', '2025-11-03T20:14:31.866Z', '2025-11-03T20:14:31.866Z') ON CONFLICT (id) DO UPDATE SET eventName = EXCLUDED.eventName, checkInLocation = EXCLUDED.checkInLocation, volunteerId = EXCLUDED.volunteerId, eventId = EXCLUDED.eventId, createdAt = EXCLUDED.createdAt, volunteerName = EXCLUDED.volunteerName, volunteerEmail = EXCLUDED.volunteerEmail, status = EXCLUDED.status, updatedAt = EXCLUDED.updatedAt, checkInTime = EXCLUDED.checkInTime;
INSERT INTO volunteer_hours (id, volunteerId, status, createdAt, checkOutLocation, updatedAt, volunteerEmail, totalHours, checkInTime, checkInLocation, checkOutTime, volunteerName, eventId, eventName) VALUES ('mbGsRVb0fbN7IxKOjBXR', 'PBGCLV', 'checked-out', '2025-10-28T22:59:15.026Z', '{"latitude":28.8129024,"longitude":-81.26464,"_type":"geopoint"}'::jsonb, '2025-10-28T23:06:02.647Z', 'ing.jod@gmail.com', 0.11, '2025-10-28T22:59:15.026Z', '{"latitude":28.8129024,"longitude":-81.26464,"_type":"geopoint"}'::jsonb, '2025-10-28T23:06:02.647Z', 'Jod', 'taste-of-korea-preparation', 'Taste of Korea - Pre-Event Preparation Period') ON CONFLICT (id) DO UPDATE SET volunteerId = EXCLUDED.volunteerId, status = EXCLUDED.status, createdAt = EXCLUDED.createdAt, checkOutLocation = EXCLUDED.checkOutLocation, updatedAt = EXCLUDED.updatedAt, volunteerEmail = EXCLUDED.volunteerEmail, totalHours = EXCLUDED.totalHours, checkInTime = EXCLUDED.checkInTime, checkInLocation = EXCLUDED.checkInLocation, checkOutTime = EXCLUDED.checkOutTime, volunteerName = EXCLUDED.volunteerName, eventId = EXCLUDED.eventId, eventName = EXCLUDED.eventName;

COMMIT;

